### ISSUE TITLE
kubeadm_config_patches does not apply?

### ISSUE THREAD

**Issue by antoinewk** [tehcyx/terraform-provider-kind#65]
Hello, first thanks for the provider.

I am having some issue with `kubeadm_config_patches ` and wonder if the format I am using is supported.

I have a kind cluster with the following yaml config file:
```
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4

nodes:
  - role: control-plane
  - role: worker

kubeadmConfigPatchesJSON6902:
  - group: kubeadm.k8s.io
    version: v1beta3
    kind: ClusterConfiguration
    patch: |
      - op: add
        path: /apiServer/certSANs/-
        value: host.docker.internal
```
This cluster can be created with: `kind create cluster --config=config.yaml`.
And the `kubeadmConfigPatchesJSON6902 ` allows for communication between a docker service and the kind cluster through the address `host.docker.internal`, documented here: https://github.com/kubernetes-sigs/kind/issues/2878.

I am trying to do the same, but with `terraform`. For that matter, I now have the following `kind.tf`:
```
resource "kind_cluster" "default" {
    name            = "test-cluster"
    node_image      = "kindest/node:v1.27.1"
    wait_for_ready  = true

    kind_config {
        kind        = "Cluster"
        api_version = "kind.x-k8s.io/v1alpha4"

        node {
            role = "control-plane"
            kubeadm_config_patches = [
"kind: ClusterConfiguration\npatch: |\n  - op: add\n    path: /apiServer/certSANs/-\n    value: host.docker.internal"
            ]
        }

        node {
            role = "worker"
            kubeadm_config_patches = [
"kind: ClusterConfiguration\npatch: |\n  - op: add\n    path: /apiServer/certSANs/-\n    value: host.docker.internal"
            ]
        }
    }
}
```
which makes use of `kubeadm_config_patches `. 
And `terraform apply` can created the resources without errors.

However, this does not seem to fully work as I face the same issue as when the patch was not applied:
```
[2024-06-04, 09:55:24 UTC] {connection.py:547} WARNING - Certificate did not match expected hostname: host.docker.internal. Certificate: {'subject': ((('commonName', 'kube-apiserver'),),), 'issuer': ((('commonName', 'kubernetes'),),), 'version': 3, 'serialNumber': '513552FCF5035527', 'notBefore': 'Jun  4 09:43:24 2024 GMT', 'notAfter': 'Jun  4 09:43:24 2025 GMT', 'subjectAltName': (('DNS', 'kubernetes'), ('DNS', 'kubernetes.default'), ('DNS', 'kubernetes.default.svc'), ('DNS', 'kubernetes.default.svc.cluster.local'), ('DNS', 'localhost'), ('DNS', 'test-cluster-control-plane'), ('IP Address', '10.96.0.1'), ('IP Address', '172.19.0.3'), ('IP Address', '127.0.0.1'))}
``` 

Any ideas?

**Comment by antoinewk** [comment]
Checking the file `/kind/kubeadm.conf`. On a kind worker created with `kind create`:
```
apiServer:
  certSANs:
  - localhost
  - 127.0.0.1
  - host.docker.internal
  extraArgs:
    runtime-config: ""
apiVersion: kubeadm.k8s.io/v1beta3
clusterName: kind
controlPlaneEndpoint: kind-control-plane:6443
controllerManager:
  extraArgs:
    enable-hostpath-provisioner: "true"
kind: ClusterConfiguration
kubernetesVersion: v1.29.2
networking:
  podSubnet: 10.244.0.0/16
  serviceSubnet: 10.96.0.0/16
scheduler:
  extraArgs: null
---
```

And with `terraform`:
```
apiServer:
  certSANs:
  - localhost
  - 127.0.0.1
  extraArgs:
    runtime-config: ""
apiVersion: kubeadm.k8s.io/v1beta3
clusterName: test-cluster
controlPlaneEndpoint: test-cluster-control-plane:6443
controllerManager:
  extraArgs:
    enable-hostpath-provisioner: "true"
kind: ClusterConfiguration
kubernetesVersion: v1.27.1
networking:
  podSubnet: 10.244.0.0/16
  serviceSubnet: 10.96.0.0/16
patch: |-
  - op: add
    path: /apiServer/certSANs/-
    value: host.docker.internal
scheduler:
  extraArgs: null
---
```

The certSANs list is not updated.
